In [11]:
from __future__ import print_function
import torch
import numpy as np
import 
x=torch.Tensor(5,3)
print(x)
a=np.random.random((5,3))
print(a)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
[[0.00299127 0.14088491 0.70313719]
 [0.32449283 0.26996205 0.56542789]
 [0.60703908 0.91874881 0.22546444]
 [0.81107949 0.56870201 0.06628772]
 [0.22367861 0.74916209 0.46142624]]


In [2]:
x=torch.rand(5,3)
print(x)

tensor([[0.4936, 0.3758, 0.4848],
        [0.2451, 0.2233, 0.5404],
        [0.7283, 0.5875, 0.7872],
        [0.8648, 0.6902, 0.7083],
        [0.5295, 0.6034, 0.7351]])


In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y=torch.Tensor(5,3)
print(x+y)

tensor([[-9.2641e+08,  3.7579e-01,  4.8482e-01],
        [ 2.4505e-01,  2.2327e-01,  5.4044e-01],
        [ 7.2830e-01,  5.8749e-01,  2.7909e+23],
        [ 8.6481e-01,  6.9020e-01,  7.0830e-01],
        [ 5.2947e-01,  6.0343e-01,  7.3515e-01]])


In [6]:
print(torch.add(x,y))

tensor([[-9.2641e+08,  3.7579e-01,  4.8482e-01],
        [ 2.4505e-01,  2.2327e-01,  5.4044e-01],
        [ 7.2830e-01,  5.8749e-01,  2.7909e+23],
        [ 8.6481e-01,  6.9020e-01,  7.0830e-01],
        [ 5.2947e-01,  6.0343e-01,  7.3515e-01]])


In [7]:
result=torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-9.2641e+08,  3.7579e-01,  4.8482e-01],
        [ 2.4505e-01,  2.2327e-01,  5.4044e-01],
        [ 7.2830e-01,  5.8749e-01,  2.7909e+23],
        [ 8.6481e-01,  6.9020e-01,  7.0830e-01],
        [ 5.2947e-01,  6.0343e-01,  7.3515e-01]])


In [8]:
y.add_(x)
print(y)

tensor([[-9.2641e+08,  3.7579e-01,  4.8482e-01],
        [ 2.4505e-01,  2.2327e-01,  5.4044e-01],
        [ 7.2830e-01,  5.8749e-01,  2.7909e+23],
        [ 8.6481e-01,  6.9020e-01,  7.0830e-01],
        [ 5.2947e-01,  6.0343e-01,  7.3515e-01]])


In [12]:
print(x[:,1])
print(a[:,1])

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
[0.14088491 0.26996205 0.91874881 0.56870201 0.74916209]


In [13]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print('torch ones:',a,'\nnumpy ones:',b)

torch ones: tensor([2., 2., 2., 2., 2.]) 
numpy ones: [2. 2. 2. 2. 2.]


In [21]:
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,b,out=a)
print('numpy ones:',a,'\ntorch ones:',b)

numpy ones: [2. 2. 2. 2. 2.] 
torch ones: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [41]:
from torch.autograd import Variable
x=Variable(torch.ones(2,2),requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [42]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [43]:
print(y.grad_fn)

In [44]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [45]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [55]:
x=torch.randn(3)
x=Variable(x,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
print(x,y)

tensor([-0.6080, -1.7878, -0.0900], requires_grad=True) tensor([ -622.5453, -1830.7483,   -92.1573], grad_fn=<MulBackward>)


In [56]:
gradients=torch.FloatTensor([0.1,1.0,0.0001])
y.backward(gradients)
print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


In [7]:
import torch
from __future__ import print_function

In [8]:
x=torch.tensor([5.5,3])
print(x)
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5852, -0.0835,  0.7588],
        [ 0.0440,  0.4237,  0.9986],
        [-0.5807, -0.0529, -1.1133],
        [ 0.3092, -0.3419,  0.4941],
        [-0.6463,  0.4473, -0.8470]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y=torch.rand(5,3)
print(y)

tensor([[0.4999, 0.6259, 0.4547],
        [0.9363, 0.8119, 0.0429],
        [0.2703, 0.3740, 0.0590],
        [0.6524, 0.1654, 0.3373],
        [0.6896, 0.1425, 0.6577]])


In [11]:
print(x+y)

tensor([[ 1.0850,  0.5424,  1.2135],
        [ 0.9803,  1.2356,  1.0415],
        [-0.3104,  0.3211, -1.0543],
        [ 0.9616, -0.1765,  0.8314],
        [ 0.0433,  0.5898, -0.1893]])


In [12]:
print(torch.add(x,y))

tensor([[ 1.0850,  0.5424,  1.2135],
        [ 0.9803,  1.2356,  1.0415],
        [-0.3104,  0.3211, -1.0543],
        [ 0.9616, -0.1765,  0.8314],
        [ 0.0433,  0.5898, -0.1893]])


In [13]:
result=torch.empty(5,3)
print(result)
torch.add(x,y,out=result)
print(result)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[ 1.0850,  0.5424,  1.2135],
        [ 0.9803,  1.2356,  1.0415],
        [-0.3104,  0.3211, -1.0543],
        [ 0.9616, -0.1765,  0.8314],
        [ 0.0433,  0.5898, -0.1893]])


In [14]:
y.add_(x)
print(y)

tensor([[ 1.0850,  0.5424,  1.2135],
        [ 0.9803,  1.2356,  1.0415],
        [-0.3104,  0.3211, -1.0543],
        [ 0.9616, -0.1765,  0.8314],
        [ 0.0433,  0.5898, -0.1893]])


In [15]:
print(x[:,1])

tensor([-0.0835,  0.4237, -0.0529, -0.3419,  0.4473])


In [17]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
a=x.view(8,-1)
print(x.size(),y.size(),z.size(),a.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([8, 2])


In [18]:
x=torch.rand(1)
print(x)
print(x.item())

tensor([0.7537])
0.7537130117416382


In [20]:
x=torch.Tensor([[1,2,3],[3,4,2]])
print(x)
y=x.numpy()
print(y)

tensor([[1., 2., 3.],
        [3., 4., 2.]])
[[1. 2. 3.]
 [3. 4. 2.]]


In [22]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
np.add(a,b,out=a)
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [43]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [28]:
print(y.grad_fn)

In [29]:
print(y.requires_grad)

True


In [44]:
z=y*y*3
out=torch.mean(z)
print(z,out)
a=torch.Tensor([[1,2],[3,4]])
print(a.mean())

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)
tensor(2.5000)


In [36]:
a=torch.randn(2,2)
print(a.requires_grad,a.grad_fn)
a.requires_grad_(True)
a=a*3/(a-1)
print(a.grad_fn)

False None


In [37]:
b=(a*a).sum()
print(b.grad_fn)

In [45]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [52]:
x=torch.randn(3,requires_grad=True)
print(x,x.data,x.data.norm())
y=x*2
while y.data.norm() <1000:
    y=y*2
print(y)

tensor([-0.8765,  1.5079,  1.3185], requires_grad=True) tensor([-0.8765,  1.5079,  1.3185]) tensor(2.1865)
tensor([-448.7554,  772.0570,  675.0931], grad_fn=<MulBackward>)


In [53]:
gradients=torch.tensor([0.3,1.0,0.0001],dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([153.6000, 512.0000,   0.0512])


In [56]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
